set(GRAPHVIZ_GRAPH_TYPE "digraph" CACHE STRING "The graph type. one of 'graph', 'digraph', 'strict graph', 'strict digraph'.")
set(GRAPHVIZ_GRAPH_NAME "MtSparked Dependencies" CACHE STRING "The graph name.")
set(GRAPHVIZ_NODE_PREFIX "target" CACHE STRING "The prefix for each node in the graphviz file.")
set(GRAPHVIZ_EXECUTABLES TRUE CACHE BOOL "Set this to FALSE to exclude executables from the generated graphs.")
set(GRAPHVIZ_STATIC_LIBS TRUE CACHE BOOL "Set this to FALSE to exclude static libraries from the generated graphs.")
set(GRAPHVIZ_SHARED_LIBS TRUE CACHE BOOL "Set this to FALSE to exclude shared libraries from the generated graphs.")
set(GRAPHVIZ_MODULE_LIBS TRUE CACHE BOOL "Set this to FALSE to exclude module libraries from the generated graphs.")
set(GRAPHVIZ_EXTERNAL_LIBS TRUE CACHE BOOL "Set this to FALSE to exclude external libraries from the generated graphs.")
set(GRAPHVIZ_IGNORE_TARGETS "" CACHE STRING "A list of regular expressions for ignoring targets.")
set(GRAPHVIZ_GENERATE_PER_TARGET FALSE CACHE BOOL "Set this to FALSE to exclude per target graphs foo.dot.<target>.")
set(GRAPHVIZ_GENERATE_DEPENDERS FALSE CACHE BOOL "Set this to FALSE to exclude depender graphs foo.dot.<target>.dependers.")
